import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import AntdWrapper from "./wrapper/antd";
import AntdRegistry from "@ant-design/nextjs-registry/lib/AntdRegistry";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-300`}
      >
        <AntdRegistry>
          <AntdWrapper>
            <Header />
            <div className="h-20" />
            <div className="grid w-full place-items-center">{children}</div>
            <div className="h-40" />
          </AntdWrapper>
        </AntdRegistry>
        <Toaster />
      </body>
    </html>
  );
}
